server: hub-cloud.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  browserstack.use_w3c: true
  bstack:options:
    os: OS X
    buildName: Capybara-browserstack"
    osVersion: Mojave
    sessionName: Local Session 
    projectName: Test Application
    debug: true
    local: true

browser_caps:
  - browserName: Chrome
    browserVersion: '70.0'
