server: hub-cloud.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  browserstack.use_w3c: true
  bstack:options:
    buildName: Capybara-browserstack"
    sessionName: Parallel Session 
    projectName: Test Application
    debug: true

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "internet explorer"
  -
    "browser": "safari"
